import os
import json
from google import genai
from google.genai import types
from typing import Callable, Any, List, Union
from dotenv import load_dotenv


load_dotenv()


from railroad._bindings import (
    State,
    Goal,
    LiteralGoal,
    Action,
    Fluent,
    extract_cheapest_relaxed_plan,
)

from railroad.planner import (
    MCTSPlanner,
    convert_state_to_positive_preconditions,
    convert_goal_to_positive_preconditions,
    _normalize_goal,
)

def _clean_fluent_str(f_str: str) -> str:
    if f_str.startswith("(not-"):
        return "(not " + f_str[5:]
    return f_str

class HeuristicContextBuilder:
    """
    Builds a structured context of the current state and relaxed planning graph (RPG)
    costs, which can be fed to an LLM to evaluate or rerank actions.
    """
    def __init__(self, fluent_filter: Callable[[Fluent], bool] | None = None):
        self.fluent_filter = fluent_filter

    def _extract_relaxed_plan(self, state: State, goal: Union[Goal, Fluent], all_actions: list[Action]) -> list[dict[str, Any]]:
        if isinstance(goal, Fluent):
            goal = LiteralGoal(goal)
            
        raw_plan = extract_cheapest_relaxed_plan(state, goal, all_actions)
        
        relaxed_plan = []
        for step in raw_plan:
            achieves_fluent, action_name, exec_cost, wait_cost, preconds = step
            relaxed_plan.append({
                "achieves_fluent": _clean_fluent_str(achieves_fluent),
                "action": action_name,
                "exec_cost": exec_cost,
                "wait_cost": wait_cost,
                "requires_preconditions": [_clean_fluent_str(p) for p in preconds]
            })
            
        return relaxed_plan

    def build_context(self, state: State, goal: Union[Goal, Fluent], actions: list[Action]) -> dict[str, Any]:
        """
        Build a dictionary containing the context for the LLM.
        """
        # Preprocess to handle negative fluents correctly in the relaxed graph
        mcts = MCTSPlanner(actions)
        norm_goal = _normalize_goal(goal)
        mcts._ensure_mapping_includes_goal(norm_goal)

        converted_state = convert_state_to_positive_preconditions(state, mcts._current_mapping)
        converted_goal = convert_goal_to_positive_preconditions(norm_goal, mcts._current_mapping)
        converted_actions = mcts._converted_actions

        current_fluents = state.fluents
        if self.fluent_filter:
            current_fluents = {f for f in current_fluents if self.fluent_filter(f)}

        goal_str = str(goal)
        if isinstance(goal, LiteralGoal):
            goal_str = str(goal.fluent())
        elif isinstance(goal, Fluent):
            goal_str = str(goal)

        plan = self._extract_relaxed_plan(converted_state, converted_goal, converted_actions)
        plan.reverse()
        
        filtered_plan = []
        for step in plan:
            if "no_op" in step["action"] and step["wait_cost"] == 0:
                continue
            filtered_plan.append(step)

        return {
            "current_time": state.time,
            "current_fluents": [_clean_fluent_str(str(f)) for f in current_fluents],
            "goal": _clean_fluent_str(goal_str),
            "cheapest_relaxed_plan": filtered_plan
        }

    def to_json(self, state: State, goal: Union[Goal, Fluent], actions: list[Action], **kwargs) -> str:
        """
        Returns a JSON string of the context.
        """
        context = self.build_context(state, goal, actions)
        return json.dumps(context, indent=2)


class LLMActionReranker:
    """
    Reranks candidate actions using an LLM by providing it with the structured
    context generated by HeuristicContextBuilder.
    """
    def __init__(
        self, 
        context_builder: HeuristicContextBuilder,
        model_name: str = "gemini-2.5-flash" # gemini-3-flash-preview
    ):
        self.context_builder = context_builder
        self.api_key = os.environ.get("GEMINI_API_KEY")
        self.client = None
        if self.api_key:
            self.client = genai.Client(api_key=self.api_key)
            self.model_name = model_name
            # self.client = None # User mock

    def rerank(self, state: State, goal: Union[Goal, Fluent], actions: list[Action], candidate_actions: list[Action]) -> list[Action]:
        """
        Takes the current state, goal, all actions, and a list of valid candidate_actions to evaluate.
        Uses an LLM to rank the candidate_actions based on the context.
        """
        # 1. Build context
        context_json = self.context_builder.to_json(state, goal, actions)
        
        # 2. Build prompt
        candidate_names = [a.name for a in candidate_actions]
        prompt = f"""You are an expert planning heuristic. You are given the current state of a system and a goal.
Your task is to rank the available candidate actions based on how effectively they help achieve the goal.

Context (JSON):
{context_json}

Candidate Actions:
{json.dumps(candidate_names, indent=2)}

Please return a JSON list of action names ordered from best to worst. Do not include markdown blocks like ```json. Just return the raw JSON array.
"""
        
        # 3. Call LLM
        if self.client:
            try:
                print(f"[LLMActionReranker] Calling Gemini API (prompt length: {len(prompt)})...")
                response = self.client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=0.0,
                        response_mime_type="application/json",
                    )
                )
                
                # Parse the response text as JSON
                ranked_names = json.loads(response.text)
                
                # Reorder candidate_actions based on the returned names
                name_to_action = {a.name: a for a in candidate_actions}
                ranked_actions = []
                for name in ranked_names:
                    if name in name_to_action:
                        ranked_actions.append(name_to_action[name])
                
                # Append any actions that the LLM might have missed to ensure no actions are lost
                for a in candidate_actions:
                    if a not in ranked_actions:
                        ranked_actions.append(a)
                
                return ranked_actions
                
            except Exception as e:
                print(f"[LLMActionReranker] Gemini API call failed: {e}. Falling back to original order.")
                return candidate_actions
        else:
            print(f"[LLMActionReranker] GEMINI_API_KEY not set or google-generativeai missing. Prompt length: {len(prompt)}. (LLM call mocked)")
            return candidate_actions
