import os
import json
from google import genai
from google.genai import types
from typing import Callable, Any, List, Union
from dotenv import load_dotenv


load_dotenv()


from railroad._bindings import (
    State,
    Goal,
    LiteralGoal,
    Action,
    Fluent,
    extract_cheapest_relaxed_plan,
)

from railroad.planner import (
    MCTSPlanner,
    convert_state_to_positive_preconditions,
    convert_goal_to_positive_preconditions,
    _normalize_goal,
)

def _clean_fluent_str(f_str: str) -> str:
    if f_str.startswith("(not-"):
        return "(not " + f_str[5:]
    return f_str

class HeuristicContextBuilder:
    """
    Builds a structured context of the current state and relaxed planning graph (RPG)
    costs, which can be fed to an LLM to evaluate or rerank actions.
    """
    def __init__(self, fluent_filter: Callable[[Fluent], bool] | None = None):
        self.fluent_filter = fluent_filter

    def _extract_relaxed_plan(self, state: State, goal: Union[Goal, Fluent], all_actions: list[Action]) -> list[dict[str, Any]]:
        if isinstance(goal, Fluent):
            goal = LiteralGoal(goal)
            
        raw_plan = extract_cheapest_relaxed_plan(state, goal, all_actions)
        
        relaxed_plan = []
        for step in raw_plan:
            achieves_fluent, action_name, exec_cost, wait_cost, preconds = step
            relaxed_plan.append({
                "achieves_fluent": _clean_fluent_str(achieves_fluent),
                "action": action_name,
                "exec_cost": exec_cost,
                "wait_cost": wait_cost,
                "requires_preconditions": [_clean_fluent_str(p) for p in preconds]
            })
            
        return relaxed_plan

    def build_context(self, state: State, goal: Union[Goal, Fluent], actions: list[Action]) -> dict[str, Any]:
        """
        Build a dictionary containing the context for the LLM.
        """
        # Preprocess to handle negative fluents correctly in the relaxed graph
        mcts = MCTSPlanner(actions)
        norm_goal = _normalize_goal(goal)
        mcts._ensure_mapping_includes_goal(norm_goal)

        converted_state = convert_state_to_positive_preconditions(state, mcts._current_mapping)
        converted_goal = convert_goal_to_positive_preconditions(norm_goal, mcts._current_mapping)
        converted_actions = mcts._converted_actions

        current_fluents = state.fluents
        if self.fluent_filter:
            current_fluents = {f for f in current_fluents if self.fluent_filter(f)}

        goal_str = str(goal)
        if isinstance(goal, LiteralGoal):
            goal_str = str(goal.fluent())
        elif isinstance(goal, Fluent):
            goal_str = str(goal)

        plan = self._extract_relaxed_plan(converted_state, converted_goal, converted_actions)
        plan.reverse()
        
        filtered_plan = []
        for step in plan:
            if "no_op" in step["action"] and step["wait_cost"] == 0:
                continue
            filtered_plan.append(step)

        return {
            "current_time": state.time,
            "current_fluents": [_clean_fluent_str(str(f)) for f in current_fluents],
            "goal": _clean_fluent_str(goal_str),
            "cheapest_relaxed_plan": filtered_plan
        }

    def to_json(self, state: State, goal: Union[Goal, Fluent], actions: list[Action], **kwargs) -> str:
        """
        Returns a JSON string of the context.
        """
        context = self.build_context(state, goal, actions)
        return json.dumps(context, indent=2)


class LLMActionReranker:
    """
    Reranks candidate actions using an LLM by providing it with the structured
    context generated by HeuristicContextBuilder.
    """
    def __init__(
        self, 
        context_builder: HeuristicContextBuilder,
        model_name: str = "gemini-2.5-flash" # gemini-3-flash-preview
    ):
        self.context_builder = context_builder
        self.api_key = os.environ.get("GEMINI_API_KEY")
        self.client = None
        if self.api_key:
            self.client = genai.Client(api_key=self.api_key)
            self.model_name = model_name
            # self.client = None # User mock

    def rerank(self, state: State, goal: Union[Goal, Fluent], actions: list[Action], candidate_actions: list[Action]) -> list[Action]:
        """
        Takes the current state, goal, all actions, and a list of valid candidate_actions to evaluate.
        Uses an LLM to rank the candidate_actions based on the context.
        """
        # 1. Build context
        context_json = self.context_builder.to_json(state, goal, actions)
        
        # 2. Build prompt
        candidate_names = [a.name for a in candidate_actions]
        prompt = f"""You are an expert planning heuristic. You are given the current state of a system and a goal.
Your task is to rank the available candidate actions based on how effectively they help achieve the goal.

Context (JSON):
{context_json}

Candidate Actions:
{json.dumps(candidate_names, indent=2)}

Please return a JSON list of action names ordered from best to worst. Do not include markdown blocks like ```json. Just return the raw JSON array.
"""
        
        # 3. Call LLM
        if self.client:
            try:
                print(f"[LLMActionReranker] Calling Gemini API (prompt length: {len(prompt)})...")
                response = self.client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=0.0,
                        response_mime_type="application/json",
                    )
                )
                
                # Parse the response text as JSON
                ranked_names = json.loads(response.text)
                
                # Reorder candidate_actions based on the returned names
                name_to_action = {a.name: a for a in candidate_actions}
                ranked_actions = []
                for name in ranked_names:
                    if name in name_to_action:
                        ranked_actions.append(name_to_action[name])
                
                # Append any actions that the LLM might have missed to ensure no actions are lost
                for a in candidate_actions:
                    if a not in ranked_actions:
                        ranked_actions.append(a)
                
                return ranked_actions
                
            except Exception as e:
                print(f"[LLMActionReranker] Gemini API call failed: {e}. Falling back to original order.")
                return candidate_actions
        else:
            print(f"[LLMActionReranker] GEMINI_API_KEY not set or google-generativeai missing. Prompt length: {len(prompt)}. (LLM call mocked)")
            return candidate_actions


class LLMHeuristicGenerator:
    """
    Constructs prompt and calls the Gemini API to generate custom heuristic function candidates.
    """
    def __init__(self, model_name: str = "gemini-2.5-pro"):
        self.api_key = os.environ.get("GEMINI_API_KEY")
        self.client = None
        if self.api_key:
            self.client = genai.Client(api_key=self.api_key)
            self.model_name = model_name

    def generate_prompt(self, domain_pddl: str, problem_pddl: str, rpg_context_json: str) -> str:
        return f"""You are an expert AI planning researcher writing a heuristic function in Python.
Your goal is to write a custom heuristic class that inherits from `Heuristic` to guide a concurrent multi-agent MCTS planner.

Here is the PDDL-like domain description:
{domain_pddl}

Here is the problem definition:
{problem_pddl}

Here is an example of the Relaxed Planning Graph (RPG) cheapest plan extracted from the initial state:
{rpg_context_json}

Your custom heuristic class must:
1. Inherit from `Heuristic` (imported as `from railroad.core import Heuristic`).
2. Implement `__call__(self, state, goal, rpg)` which:
   - Takes a `State` object `state`.
   - Takes a `Goal` object `goal`.
   - Takes a dict `rpg` (described below).
   - Returns a `float` representing the estimated cost to reach the goal.
3. Not hardcode values specific to the initial state; it must generalize.
4. Return lower values for states closer to achieving the goal, and higher values for dead ends or states further away.

Here is the exact Python API of the objects you will be working with:
- `state`: Has property `state.fluents` which is a set of `Fluent` objects.
- `fluent` object:
  - `fluent.name`: The predicate name (string, e.g. "at" or "holding" or "free").
  - `fluent.args`: A list/tuple of string arguments (e.g. ["robot1", "table"]).
  - `fluent.negated`: A boolean indicating if the fluent is negated.
  - To inspect a fluent, use its properties, e.g., checking `fluent.name == "holding" and "Mug" in fluent.args`.
- `goal` object:
  - `goal.evaluate(state.fluents)`: Returns a boolean indicating if the goal is fully satisfied.
  - `goal.goal_count(state.fluents)`: Returns an integer count of how many goals are achieved.
- `rpg` dictionary:
  - `rpg["cheapest_relaxed_plan"]`: A list of steps (actions in the relaxed plan). Each step is a dict:
    - `step["achieves_fluent"]`: string representation of the achieved fluent (e.g. "(at robot1 cabinet)")
    - `step["action"]`: string name of the action (e.g. "move robot1 start_loc cabinet")
    - `step["exec_cost"]`: float duration of the action execution
    - `step["wait_cost"]`: float wait cost for preconditions to be satisfied
    - `step["requires_preconditions"]`: list of precondition strings

Examples of how to import needed modules:
Make sure to include any needed imports (e.g., `import re` or `from railroad.core import Fluent`) inside your code block if you use them.

Please return ONLY the Python code containing the class definition. Do not include markdown formatting like ```python or ```. Just the raw Python code.
"""


    def generate_heuristic_candidates(self, prompt: str, n: int = 5) -> list[str]:
        candidates = []
        if not self.client:
            print("[LLMHeuristicGenerator] GEMINI_API_KEY not set. Cannot generate heuristics.")
            return candidates

        import time
        # List of models to try in case of failure (spikes/availability)
        models_to_try = [self.model_name, "gemini-2.5-flash", "gemini-1.5-flash"]
        # De-duplicate to preserve order
        models_to_try = list(dict.fromkeys(models_to_try))

        for i in range(n):
            success = False
            for model in models_to_try:
                for attempt in range(3):
                    try:
                        print(f"[LLMHeuristicGenerator] Generating candidate {i+1}/{n} using {model} (attempt {attempt+1})...")
                        response = self.client.models.generate_content(
                            model=model,
                            contents=prompt,
                            config=types.GenerateContentConfig(
                                temperature=0.8, # high temperature for diversity
                            )
                        )
                        code = response.text.strip()
                        # Clean up markdown code block if LLM returned it anyway
                        if code.startswith("```python"):
                            code = code[9:]
                        if code.endswith("```"):
                            code = code[:-3]
                        candidates.append(code.strip())
                        success = True
                        break
                    except Exception as e:
                        print(f"Attempt {attempt+1} failed with error: {e}")
                        if "503" in str(e) or "RESOURCE_EXHAUSTED" in str(e):
                            time.sleep(2 * (attempt + 1))
                        else:
                            break # Non-temporary error
                if success:
                    break
            if not success:
                print(f"Failed to generate candidate {i+1} after trying all fallback models.")
        return candidates


class SandboxEvaluator:
    """
    Runs the Tournament to evaluate generated Python heuristic code candidates.
    """
    def __init__(self, actions: list[Action], initial_state: State, goal: Goal, max_iterations: int = 1000):
        self.actions = actions
        self.initial_state = initial_state
        self.goal = goal
        self.max_iterations = max_iterations

    def evaluate_candidate(self, code_str: str) -> dict[str, Any]:
        """
        Compiles and evaluates a single heuristic candidate by simulating an MCTS run.
        """
        result = {
            "success": False,
            "error": None,
            "steps_taken": 9999,
        }

        # Sandbox dict
        loc = {}
        try:
            # 1. Compile the code
            exec(code_str, globals(), loc)
            
            # Find the class that inherits from Heuristic or is a class
            from railroad.core import Heuristic
            heuristic_class = None
            for key, val in loc.items():
                if isinstance(val, type) and val.__name__ != "Heuristic":
                    heuristic_class = val
                    break
                    
            if not heuristic_class:
                raise ValueError("No class found in generated code.")
                
            # 2. Instantiate
            custom_h = heuristic_class()
            
            # 3. Create a planner using the custom heuristic
            mcts = MCTSPlanner(self.actions, custom_heuristic=custom_h)
            
            # 4. Run the planning tournament
            state = self.initial_state
            step_count = 0
            success = False
            
            from railroad.core import get_action_by_name, transition
            
            # Simulate execution loop
            for step in range(30):
                if self.goal.evaluate(state.fluents):
                    success = True
                    break
                action_name = mcts(state, self.goal, max_iterations=self.max_iterations, c=10.0)
                if action_name == "NONE":
                    break
                
                action = get_action_by_name(self.actions, action_name)
                state = transition(state, action)[0][0]
                step_count += 1
                
            result["success"] = success
            result["steps_taken"] = step_count
            
        except Exception as e:
            result["error"] = str(e)
            
        return result

    def run_tournament(self, candidates: list[str]) -> tuple[str | None, int]:
        """
        Runs evaluation on all candidates and returns the best candidate's code.
        """
        best_code = None
        best_steps = 9999
        
        for idx, candidate in enumerate(candidates):
            print(f"Evaluating Candidate {idx + 1}...")
            res = self.evaluate_candidate(candidate)
            if res["success"]:
                print(f"Candidate {idx + 1} succeeded in {res['steps_taken']} steps!")
                if res["steps_taken"] < best_steps:
                    best_steps = res["steps_taken"]
                    best_code = candidate
            else:
                print(f"Candidate {idx + 1} failed or errored: {res['error']}")
                
        return best_code, best_steps

