import os
import json
from typing import Callable, Any, List, Union

try:
    import google.generativeai as genai
    HAS_GENAI = True
except ImportError:
    HAS_GENAI = False

from railroad._bindings import (
    State,
    Goal,
    LiteralGoal,
    Action,
    Fluent,
    get_relaxed_expected_cost,
    get_achievers_for_fluent,
)

class HeuristicContextBuilder:
    """
    Builds a structured context of the current state and relaxed planning graph (RPG)
    costs, which can be fed to an LLM to evaluate or rerank actions.
    """
    def __init__(self, fluent_filter: Callable[[Fluent], bool] | None = None):
        self.fluent_filter = fluent_filter

    def build_context(self, state: State, goal: Union[Goal, Fluent], actions: list[Action], top_k_achievers: int = 3) -> dict[str, Any]:
        """
        Build a dictionary containing the context for the LLM.
        """
        context: dict[str, Any] = {
            "current_time": state.time,
        }

        # Filter current state fluents
        current_fluents = state.fluents
        if self.fluent_filter:
            current_fluents = {f for f in current_fluents if self.fluent_filter(f)}
        
        context["current_fluents"] = [str(f) for f in current_fluents]

        # Normalize goal input to a Goal object
        if isinstance(goal, Fluent):
            goal = LiteralGoal(goal)

        # Get DNF branches and find missing fluents
        branches = goal.get_dnf_branches()
        branch_contexts = []
        
        for branch_fluents in branches:
            missing_fluents = [f for f in branch_fluents if f not in state.fluents]
            
            branch_info = {
                "branch_fluents": [str(f) for f in branch_fluents],
                "missing_fluents": [],
            }

            for f in missing_fluents:
                # 1. Expected relaxed cost
                cost = get_relaxed_expected_cost(state, f, actions)
                is_reachable = cost != float("inf")

                # 2. Achievers
                raw_achievers = get_achievers_for_fluent(state, f, actions)
                
                # Sort achievers by attempt cost (wait_cost + exec_cost)
                # achiever tuple: (action_name, wait_cost, exec_cost, probability)
                sorted_achievers = sorted(
                    raw_achievers,
                    key=lambda a: a[1] + a[2]
                )
                
                # Take top K
                top_achievers = [
                    {
                        "action_name": a[0],
                        "wait_cost": a[1],
                        "exec_cost": a[2],
                        "probability": a[3],
                    }
                    for a in sorted_achievers[:top_k_achievers]
                ]

                fluent_info = {
                    "fluent": str(f),
                    "expected_cost": cost if is_reachable else None,
                    "is_reachable": is_reachable,
                    "top_achievers": top_achievers,
                }
                branch_info["missing_fluents"].append(fluent_info)
            
            branch_contexts.append(branch_info)
        
        context["goal_branches"] = branch_contexts

        return context

    def to_json(self, state: State, goal: Union[Goal, Fluent], actions: list[Action], top_k_achievers: int = 3) -> str:
        """
        Returns a JSON string of the context.
        """
        context = self.build_context(state, goal, actions, top_k_achievers)
        return json.dumps(context, indent=2)


class LLMActionReranker:
    """
    Reranks candidate actions using an LLM by providing it with the structured
    context generated by HeuristicContextBuilder.
    """
    def __init__(self, context_builder: HeuristicContextBuilder, model_name: str = "gemini-2.5-flash"):
        self.context_builder = context_builder
        self.api_key = os.environ.get("GEMINI_API_KEY")
        self.model = None
        if self.api_key and HAS_GENAI:
            genai.configure(api_key=self.api_key)
            self.model = genai.GenerativeModel(model_name)
        elif self.api_key and not HAS_GENAI:
            print("[LLMActionReranker] Warning: GEMINI_API_KEY is set but google-generativeai package is not installed.")

    def rerank(self, state: State, goal: Union[Goal, Fluent], actions: list[Action], candidate_actions: list[Action]) -> list[Action]:
        """
        Takes the current state, goal, all actions, and a list of valid candidate_actions to evaluate.
        Uses an LLM to rank the candidate_actions based on the context.
        """
        # 1. Build context
        context_json = self.context_builder.to_json(state, goal, actions)
        
        # 2. Build prompt
        candidate_names = [a.name for a in candidate_actions]
        prompt = f"""You are an expert planning heuristic. You are given the current state of a system and a goal.
Your task is to rank the available candidate actions based on how effectively they help achieve the goal.

Context (JSON):
{context_json}

Candidate Actions:
{json.dumps(candidate_names, indent=2)}

Please return a JSON list of action names ordered from best to worst. Do not include markdown blocks like ```json. Just return the raw JSON array.
"""
        
        # 3. Call LLM
        if self.model:
            try:
                print(f"[LLMActionReranker] Calling Gemini API (prompt length: {len(prompt)})...")
                response = self.model.generate_content(
                    prompt,
                    generation_config=genai.types.GenerationConfig(
                        temperature=0.0,
                        response_mime_type="application/json",
                    )
                )
                
                # Parse the response text as JSON
                ranked_names = json.loads(response.text)
                
                # Reorder candidate_actions based on the returned names
                name_to_action = {a.name: a for a in candidate_actions}
                ranked_actions = []
                for name in ranked_names:
                    if name in name_to_action:
                        ranked_actions.append(name_to_action[name])
                
                # Append any actions that the LLM might have missed to ensure no actions are lost
                for a in candidate_actions:
                    if a not in ranked_actions:
                        ranked_actions.append(a)
                
                return ranked_actions
                
            except Exception as e:
                print(f"[LLMActionReranker] Gemini API call failed: {e}. Falling back to original order.")
                return candidate_actions
        else:
            print(f"[LLMActionReranker] GEMINI_API_KEY not set or google-generativeai missing. Prompt length: {len(prompt)}. (LLM call mocked)")
            return candidate_actions
