from railroad.core import Heuristic

class CustomHeuristic(Heuristic):
    """
    A custom heuristic for concurrent multi-agent MCTS planning that
    estimates the cost to reach the goal based on the makespan of a
    relaxed plan generated by an RPG.
    """

    def __call__(self, state, goal, rpg):
        """
        Estimates the cost from the current state to the goal.

        Args:
            state (State): The current state object.
            goal (Goal): The goal object.
            rpg (dict): A dictionary containing information about the
                        Relaxed Planning Graph, including the cheapest
                        relaxed plan and its associated costs.

        Returns:
            float: The estimated cost to reach the goal. Returns 0.0 if
                   the goal is already met, or float('inf') if no relaxed
                   plan can be found (indicating a dead end).
        """

        # If the goal is already satisfied in the current state, the cost is 0.
        if goal.evaluate(state.fluents):
            return 0.0

        # Retrieve the cheapest relaxed plan from the RPG.
        # If no relaxed plan is found (e.g., the goal is unreachable in the
        # relaxed problem), it's a dead end, so assign an infinite cost.
        relaxed_plan = rpg.get("cheapest_relaxed_plan")
        if not relaxed_plan:
            return float('inf')

        # For concurrent planning, the heuristic often estimates the makespan
        # (total time) of the relaxed plan.
        # Each step in the relaxed plan has an 'exec_cost' (duration of the action)
        # and a 'wait_cost' (time spent waiting for preconditions to be met,
        # relative to the current state's time).
        # The completion time of an individual action in the relaxed plan
        # is `wait_cost + exec_cost`.
        # The makespan of the entire relaxed plan is the maximum of these
        # completion times across all actions in the plan. This represents
        # the earliest time the last action in the relaxed plan can finish,
        # thereby achieving the goal.

        max_completion_time_in_relaxed_plan = 0.0
        for step in relaxed_plan:
            # Safely get costs, defaulting to 0.0 if not present (though they should be).
            wait_cost = step.get("wait_cost", 0.0)
            exec_cost = step.get("exec_cost", 0.0)

            # Calculate the completion time for this specific action within the
            # context of the relaxed plan (relative to the current state).
            action_completion_time = wait_cost + exec_cost

            # Update the maximum completion time found so far.
            if action_completion_time > max_completion_time_in_relaxed_plan:
                max_completion_time_in_relaxed_plan = action_completion_time
        
        # The heuristic value is the estimated makespan of the relaxed plan
        # from the current state to the goal.
        return max_completion_time_in_relaxed_plan